<?php
    $bvUrl = Bazaarvoice_Helper_Data::getBvUrl(true, "activeprofiles");
?>
<div id="BVSubmissionContainer">
    <img src="<?php echo $bvUrl; ?>/bv_sub_loading_60.gif" id="BVLoaderImage" width="60" height="60" alt="Loading..."/>
</div>
<script type="text/javascript" language="javascript">
   function getCPDisplayCode() {
        try {
            <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("activeprofiles", "DisplayCodeJavascript"); ?>
        }catch(e){
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "<?php echo Bazaarvoice_Helper_Data::getDisplayCodeForBVProduct("activeprofiles"); ?>";
   }

   var configData = {};
   configData.displayCode = getCPDisplayCode();
   $BV.ui("submission_container", configData);
</script>