<?php
if(Mage::getStoreConfig("bazaarvoice/SY/EnableSY") === "1") {
    //Determine if we are rendering on a product or category page
    $bvSubject = Bazaarvoice_Helper_Data::getExternalSubjectForPage($this);

    //Obtain SmartSEO content
    $smartSEOPageFormat = Mage::getStoreConfig("bazaarvoice/SY/SmartSEOPageFormat");
    $content = Bazaarvoice_Helper_Data::getSmartSEOContent("stories", $bvSubject, $smartSEOPageFormat);
?>
<div id="BVSYContainer">
    <?php echo $content; ?>
</div>
<script type="text/javascript" language="javascript">
    function getSYDisplayCode() {
        try {
            <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("stories", "DisplayCodeJavascript"); ?>
        }catch(e){
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "<?php echo Bazaarvoice_Helper_Data::getDisplayCodeForBVProduct("stories"); ?>";
    }
    function getStoriesDisplayFormat() {
        try {
            <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("stories", "DisplayFormatJavascript"); ?>
        } catch (e) {
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "show_stories";
    }
    var configData = {};
    configData.displayCode = getSYDisplayCode();
    configData.subjectType = "<?php echo $bvSubject[Bazaarvoice_Helper_Data::BV_SUBJECT_TYPE]; ?>";
    if ("<?php echo $bvSubject[Bazaarvoice_Helper_Data::BV_SUBJECT_TYPE]; ?>" === "product") {
        configData.productId = "<?php echo $bvSubject[Bazaarvoice_Helper_Data::BV_EXTERNAL_SUBJECT_ID]; ?>";
    } else {
        configData.categoryId = "<?php echo $bvSubject[Bazaarvoice_Helper_Data::BV_EXTERNAL_SUBJECT_ID]; ?>";
    }
    configData.summaryContainerDiv = "BVSYSummaryContainer";
    configData.contentContainerDiv = "BVSYContainer";
    configData.onEvent = function(json) {
        <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("stories", "OnEventJavascript") . "\n"; ?>
    };
    configData.doShowContent = function () {
    	<?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("stories", "DoShowContentJavascript") . "\n"; ?>
    };
	$BV.ui("sy", getStoriesDisplayFormat(), configData);
</script>
<?php } ?>