<?php
if(Mage::getStoreConfig("bazaarvoice/AA/EnableAA") === "1") {
    //Determine if we are rendering on a product or category page
    $bvSubject = Mage::helper('Bazaarvoice')->getExternalSubjectForPage($this);

    //Obtain SmartSEO content
    $content = Mage::helper('Bazaarvoice')->getSmartSEOContent("questions", $bvSubject, "");
?>
<div id="BVQAContainer">
    <?php echo $content; ?>
</div>
<script type="text/javascript" language="javascript">
    function getAADisplayCode() {
        try {
            <?php echo Mage::helper('Bazaarvoice')->getConfigPropertyForBVProduct("questions", "DisplayCodeJavascript"); ?>
        }catch(e){
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "<?php echo Mage::helper('Bazaarvoice')->getDisplayCodeForBVProduct("questions"); ?>";
    }
    var configData = {};
    configData.displayCode = getAADisplayCode();
    configData.subjectType = "<?php echo $bvSubject[Mage::helper('Bazaarvoice')->BV_SUBJECT_TYPE]; ?>";
    if ("<?php echo $bvSubject[Mage::helper('Bazaarvoice')->BV_SUBJECT_TYPE]; ?>" === "product") {
        configData.productId = "<?php echo $bvSubject[Mage::helper('Bazaarvoice')->BV_EXTERNAL_SUBJECT_ID]; ?>";
    } else {
        configData.categoryId = "<?php echo $bvSubject[Mage::helper('Bazaarvoice')->BV_EXTERNAL_SUBJECT_ID]; ?>";
    }
    configData.summaryContainerDiv = "BVQASummaryContainer";
    configData.contentContainerDiv = "BVQAContainer";
    configData.onEvent = function(json) {
        <?php echo Mage::helper('Bazaarvoice')->getConfigPropertyForBVProduct("questions", "OnEventJavascript") . "\n"; ?>
    };
    configData.doShowContent = function () {
    	<?php echo Mage::helper('Bazaarvoice')->getConfigPropertyForBVProduct("questions", "DoShowContentJavascript") . "\n"; ?>
    };
    $BV.ui("qa", "show_questions", configData);
</script>
<?php } ?>