<?php if(Mage::getStoreConfig("bazaarvoice/General/enable_bv") === "1"): ?>
<?php
$bvApiUrl = Mage::helper('bazaarvoice')->getBvApiHostUrl(true);
$bvFBXdReceiverUrl = Mage::getStoreConfig("bazaarvoice/General/FacebookXdReceiverUrl");

$encUserID = "";
$customerSession = Mage::getSingleton('customer/session');
if($customerSession->isLoggedIn()) {
    $encUserID = Mage::helper('bazaarvoice')->encryptReviewerId($customerSession->getCustomer()->getId());
}
?>
<script type="text/javascript" src="<?php echo $bvApiUrl ?>/bvapi.js"></script>
<script type="text/javascript" language="javascript">
    var configData = {};
    configData.userToken = "<?php echo $encUserID ?>";
    if ("<?php echo $bvFBXdReceiverUrl; ?>" != "") {
        configData.facebookXdChannelUrl = "<?php echo $bvFBXdReceiverUrl; ?>";
    }
    $BV.configure("global", configData);
</script>
<?php endif;?>