<?php if(Mage::getStoreConfig("bazaarvoice/RR/EnableRR") === "1"): ?>

<?php
    //Determine if we are rendering on a product or category page
    $bvSubject = Mage::helper('bazaarvoice')->getExternalSubjectForPage($this);

    //Obtain SmartSEO content
    //$content = Mage::helper('bazaarvoice')->getSmartSEOContent("reviews", $bvSubject, "");

    $bvURL = Mage::helper('bazaarvoice')->getBvUrl(false, "reviews");
    $prodId = $bvSubject[Mage::helper('bazaarvoice')->BV_EXTERNAL_SUBJECT_ID];
    $prodName = $bvSubject[Mage::helper('bazaarvoice')->BV_EXTERNAL_SUBJECT_NAME];
?>

<div id="BVRRContainer">
    <?php //echo $content; ?>
</div>
<div id="BVRRLinkContainer"><a href="<?php echo $bvURL . "/" . $prodId; ?>/reviews.htm">Read all <?php echo $prodName; ?> reviews</a></div>
<script type="text/javascript" language="javascript">
</script>

<?php endif; ?>
