<?php
if(Mage::getStoreConfig("bazaarvoice/RR/EnableRR") === "1") {
    //Determine if we are rendering on a product or category page
    $bvSubject = Bazaarvoice_Helper_Data::getExternalSubjectForPage($this);

    //Obtain SmartSEO content
    $content = Bazaarvoice_Helper_Data::getSmartSEOContent("reviews", $bvSubject, "");

    $bvURL = Bazaarvoice_Helper_Data::getBvUrl(false, "reviews");
    $prodId = $bvSubject[Bazaarvoice_Helper_Data::BV_EXTERNAL_SUBJECT_ID];
    $prodName = $bvSubject[Bazaarvoice_Helper_Data::BV_EXTERNAL_SUBJECT_NAME];
?>
<div id="BVReviewsContainer">
    <?php echo $content; ?>
</div>
<div id="BVRRLinkContainer"><a href="<?php echo $bvURL . "/" . $prodId; ?>/reviews.htm">Read all <?php echo $prodName; ?> reviews</a></div>
<script type="text/javascript" language="javascript">
    function getRRDisplayCode() {
        try {
            <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("reviews", "DisplayCodeJavascript"); ?>
        }catch(e){
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "<?php echo Bazaarvoice_Helper_Data::getDisplayCodeForBVProduct("reviews"); ?>";
    }
    function getRRDisplayType() {
        try {
            <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("reviews", "DisplayTypeJavascript"); ?>
        } catch (e) {
            //The JS in the try-catch above is user-definable.  Catch and suppress any errors and just return a default.
        }
        return "";
    }

    var configData = {};
    configData.displayCode = getRRDisplayCode();
    configData.productId = "<?php echo $bvSubject[Bazaarvoice_Helper_Data::BV_EXTERNAL_SUBJECT_ID]; ?>";
    configData.summaryContainerDiv = "BVCustomerRatings";
    configData.contentContainerDiv = "BVReviewsContainer";
    configData.onEvent = function(json) {
        <?php echo Bazaarvoice_Helper_Data::getConfigPropertyForBVProduct("reviews", "OnEventJavascript"); ?>
    };
    if (getRRDisplayType() != "") {
        configData.displayType = getRRDisplayType();
    }

    $BV.ui("rr", "show_reviews", configData);
</script>
<?php } ?>